"""
AdServiceAgent B2 Live-LLM Baseline Runner
==========================================
Runs co_helper_adservice.py 10 times with FAULT_MODE=NONE and USE_LLM=true
using qwen2.5:3b @ temperature=0.0 (matching the other pipeline B2 runs).

Saves to: results/b2_live_llm/adserviceagent_livellm_b2_run{1..10}.json
Updates:  results/b2_live_llm_variance_summary.json  (adds adserviceagent key)

Usage on SPEED (tcsh):
  setenv OLLAMA_URL http://localhost:11434
  $VENV/bin/python run_adservice_b2_live_llm.py

Usage locally (if Ollama is running):
  python run_adservice_b2_live_llm.py

Options:
  --runs N          Number of runs (default 10)
  --model MODEL     Ollama model tag (default qwen2.5:3b)
  --temp TEMP       Temperature (default 0.0)
  --ollama-url URL  Ollama base URL (default http://localhost:11434)
"""

import argparse
import json
import os
import subprocess
import sys
import traceback
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

SRC = Path(__file__).parent
HELPER = SRC / "co_helper_adservice.py"
OUT_DIR = SRC / "results" / "b2_live_llm"
SUMMARY_FILE = SRC / "results" / "b2_live_llm_variance_summary.json"
OUT_DIR.mkdir(parents=True, exist_ok=True)


# ── Variance helpers (same logic as extract_b2_live_llm.py) ──────────────────

def summarize_field(values: list) -> dict:
    unique = list({str(v): v for v in values}.values())
    all_same = len(unique) == 1
    return {
        "n_runs": len(values),
        "all_same": all_same,
        "unique_count": len(unique),
        "values": values,
        "consensus": unique[0] if all_same else None,
        "note": "zero variance (B2=B1)" if all_same else "variance present",
    }


def compute_variance(lkw_runs: list) -> dict:
    """lkw_runs: list of lkw trace lists (one per run)."""
    per_step_field: dict = defaultdict(lambda: defaultdict(list))
    for lkw in lkw_runs:
        for cp in lkw:
            step = cp["step"]
            for field, val in cp.get("data", {}).items():
                per_step_field[step][field].append(val)
    return {step: {f: summarize_field(vals)
                   for f, vals in fields.items()}
            for step, fields in per_step_field.items()}


def print_variance_report(variance: dict, agent: str, n_runs: int):
    print(f"\n{'='*70}")
    print(f"ADSERVICEAGENT B2 LIVE-LLM VARIANCE REPORT  ({n_runs} runs)")
    print(f"{'='*70}")
    for step in sorted(variance.keys()):
        for field, summary in sorted(variance[step].items()):
            flag = "  " if summary["all_same"] else "* "
            print(f"  {flag}{step}.{field}: {summary['note']}")
            if not summary["all_same"]:
                print(f"      values: {summary['values']}")


# ── Runner ────────────────────────────────────────────────────────────────────

def run_once(python: str, ollama_url: str, model: str, temp: float,
             run_num: int) -> Optional[Dict]:
    payload = json.dumps({
        "fault_mode": "NONE",
        "model": model,
        "ollama_url": ollama_url,
        "temperature": temp,
        "instruction": "show me some clothing ads",
        "context_keys": [],
    })
    try:
        result = subprocess.run(
            [python, str(HELPER), payload],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(SRC),
        )
        if result.returncode != 0:
            print(f"  [run {run_num}] ERROR (exit {result.returncode}):")
            print(f"    stderr: {result.stderr[-400:]}")
            return None
        # co_helper_adservice.py prints one JSON line at the end
        output_line = result.stdout.strip().split("\n")[-1]
        return json.loads(output_line)
    except subprocess.TimeoutExpired:
        print(f"  [run {run_num}] TIMEOUT after 120s")
        return None
    except json.JSONDecodeError as e:
        print(f"  [run {run_num}] JSON parse error: {e}")
        print(f"  stdout: {result.stdout[-300:]}")
        return None
    except Exception as e:
        print(f"  [run {run_num}] unexpected error: {e}")
        traceback.print_exc()
        return None


def save_run(run_num: int, raw: dict, model: str, temp: float) -> Path:
    out = {
        "agent": "adserviceagent",
        "b2_source": "live_llm_direct",
        "source_config": f"USE_LLM=true FAULT_MODE=NONE",
        "extraction_note": (
            "Generated by run_adservice_b2_live_llm.py calling "
            "co_helper_adservice.py with USE_LLM=true and FAULT_MODE=NONE. "
            "This is a live LLM call — NOT the deterministic test_fault_injection.py path."
        ),
        "run_idx": run_num,
        "model": model,
        "temperature": temp,
        "fault_mode": raw.get("fault_mode", "NONE"),
        "lkw": raw.get("lkw", []),
        "ads": raw.get("ads", []),
        "steps": [cp["step"] for cp in raw.get("lkw", [])],
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    fpath = OUT_DIR / f"adserviceagent_livellm_b2_run{run_num}.json"
    fpath.write_text(json.dumps(out, indent=2))
    return fpath


def update_summary(variance: dict):
    """Add/replace adserviceagent section in the shared variance summary."""
    if SUMMARY_FILE.exists():
        try:
            existing = json.loads(SUMMARY_FILE.read_text())
        except Exception:
            existing = {}
    else:
        existing = {}
    existing["adserviceagent"] = variance
    SUMMARY_FILE.write_text(json.dumps(existing, indent=2))
    print(f"\nUpdated variance summary: {SUMMARY_FILE.name}")
    print(f"  (adserviceagent section added; other {len(existing)-1} agent(s) preserved)")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="AdService B2 live-LLM runner")
    parser.add_argument("--runs", type=int, default=10, help="Number of runs")
    parser.add_argument("--model", default="qwen2.5:3b", help="Ollama model tag")
    parser.add_argument("--temp", type=float, default=0.0, help="Temperature")
    parser.add_argument(
        "--ollama-url",
        default=os.getenv("OLLAMA_URL", "http://localhost:11434"),
        help="Ollama base URL",
    )
    args = parser.parse_args()

    python = sys.executable
    print(f"Python:     {python}")
    print(f"Helper:     {HELPER}")
    print(f"Ollama URL: {args.ollama_url}")
    print(f"Model:      {args.model}")
    print(f"Temp:       {args.temp}")
    print(f"Runs:       {args.runs}")
    print(f"Output dir: {OUT_DIR}")
    print()

    if not HELPER.exists():
        print(f"ERROR: co_helper_adservice.py not found at {HELPER}")
        sys.exit(1)

    # Quick Ollama connectivity check
    import urllib.request
    try:
        with urllib.request.urlopen(args.ollama_url, timeout=5):
            pass
        print("Ollama: reachable\n")
    except Exception as e:
        print(f"WARNING: Ollama not reachable at {args.ollama_url} ({e})")
        print("  Continuing anyway — runs will timeout if Ollama is down.\n")

    lkw_runs = []
    saved_files = []

    for i in range(1, args.runs + 1):
        print(f"  Run {i:02d}/{args.runs} ...", end=" ", flush=True)
        raw = run_once(python, args.ollama_url, args.model, args.temp, i)
        if raw is None:
            print("FAILED — skipping")
            continue
        steps = [cp["step"] for cp in raw.get("lkw", [])]
        n_ads = len(raw.get("ads", []))
        print(f"OK  steps={steps}  ads={n_ads}")
        lkw_runs.append(raw.get("lkw", []))
        fpath = save_run(i, raw, args.model, args.temp)
        saved_files.append(fpath.name)

    if not lkw_runs:
        print("\nERROR: all runs failed — no output written")
        sys.exit(1)

    # Variance report
    variance = compute_variance(lkw_runs)
    print_variance_report(variance, "adserviceagent", len(lkw_runs))

    # Summary
    print(f"\n{'='*70}")
    print(f"Completed: {len(lkw_runs)}/{args.runs} runs succeeded")
    print(f"Files written:")
    for f in saved_files:
        print(f"  {f}")

    update_summary(variance)

    # Quick verdict for paper
    print(f"\n{'='*70}")
    print("PAPER TABLE F VERDICT:")
    for step, fields in sorted(variance.items()):
        for field, summary in sorted(fields.items()):
            status = "B2=B1" if summary["all_same"] else f"VARIANCE {summary['values']}"
            print(f"  {step}.{field}: {status}")


if __name__ == "__main__":
    main()
